In [32]:
import numpy as np

In [16]:
# 1. What is a Python library? Why do we use Python libraries?

In [17]:
# 2. What is the difference between Numpy array and List?

In [18]:
# 3. Find the shape, size and dimension of the following array?
#  [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]

In [35]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.shape)
arr.size

(3, 4)


12

In [19]:
# 4. Write python code to access the first row of the following array?
#  [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]

In [37]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1[0]

array([1, 2, 3, 4])

In [20]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
#  [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]

In [38]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2[2,3]

12

In [21]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
#  [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]

In [41]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3[::,1:4:2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [22]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [45]:
import random as rand

arr3 = np.random.rand(3,3)
arr3

array([[0.53272985, 0.40403153, 0.47869054],
       [0.99003468, 0.85154042, 0.57085773],
       [0.11434185, 0.02265671, 0.05851623]])

In [23]:
# 8. Describe the difference between np.random.rand and np.random.randn?

In [24]:
# 9. Write code to increase the dimension of the following array?
#  [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]

In [47]:
arr5 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np.expand_dims(arr5,axis=1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [25]:
# 10. How to transpose the following array in NumPy?
#  [[1, 2, 3, 4]

# [5, 6, 7, 8],

# [9, 10, 11, 12]]

In [61]:
arr6 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np.transpose(arr6)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [26]:
# 11. Consider the following matrix:

# Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


# Perform the following operation using Python1 
# 1.Index wise multiplicatio'
# 2. Matrix multiplicatio'
# 3. Add both the matricK
# 4. Subtract matrix B from A
# 5. Divide Matrix B by A

In [73]:
mata = np.matrix([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
matb = np.matrix([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13,14,15,16]])
print("matrix Multiplication: ",mata*matb)
arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Array Multiplication:",arr1*arr2)
matrixa = np.matrix([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
matrixb = np.matrix([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("Matrix addition",matrixa+matrixb)
print("Matrix subtraction : ",matrixa-matrixb)
print("Divide MAtrix: ",matrixa/matrixb)

matrix Multiplication:  [[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]]
Array Multiplication: [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix addition [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Matrix subtraction :  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Divide MAtrix:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

In [75]:
array = np.array([1,2,3,4],dtype='>i4')
array.byteswap()

array([16777216, 33554432, 50331648, 67108864], dtype=int32)

In [28]:
# 13. What is the significance of the np.linalg.inv function?

In [89]:
a2 = np.array([[1,2,3],[4,4,4],[7,8,10]])
np.linalg.inv(a2)

array([[-2.  , -1.  ,  1.  ],
       [ 3.  ,  2.75, -2.  ],
       [-1.  , -1.5 ,  1.  ]])

In [29]:
# 14. What does the np.reshape function do, and how is it used?

In [91]:
# np.reshape reshapes the numpy array to a new shape and returns a reshaped array
a3 = np.array([[1,2,3],[4,4,4],[7,8,10]]).reshape(1,9) # reshapes the array of shape 3,3 to 1,9
a3

array([[ 1,  2,  3,  4,  4,  4,  7,  8, 10]])

In [30]:
# 15. What is broadcasting in Numpy?

In [95]:
# Broadcasting creates additional elements in the broadcasted array to match the array to which it is broadcasted to.

a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b = np.array([11,3,4,32])
a+b

array([[12,  5,  7, 36],
       [16,  9, 11, 40],
       [20, 13, 15, 44]])